name: CD

on:
  push:
    branches:
      - main  # Set your main branch name here

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'  # Choose your preferred distribution
        java-version: '11'
        java-package: 'jdk'

    - name: Build Spring Boot Application
      run: ./mvnw clean package -DskipTests=true

    - name: Deploy to Render
      if: github.ref == 'refs/heads/main'  # Deploy only on main branch
      env:
        RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}  # Your Render token
        RENDER_SERVICE_NAME: acebook-java_team-red-panda  # Replace with your Render service name
      run: |
        curl -X PATCH -H "Authorization: Bearer $RENDER_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"buildCommand": "./mvnw spring-boot:run"}' \
          https://api.render.com/v1/services/$RENDER_SERVICE_NAME

