name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          DOWNLOAD_URL="https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.55/mac-arm64/chrome-mac-arm64.zip"
          FILENAME=$(basename "$DOWNLOAD_URL")
          wget -q -O "$FILENAME" "$DOWNLOAD_URL"
          unzip "$FILENAME"
          # Move chromedriver to /usr/local/bin/
          sudo mv chromedriver /usr/local/bin/
          # Clean up by removing the downloaded ZIP file
          rm "$FILENAME"


      - name: Build with Maven
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: mvn clean install 

      - name: Test with Maven
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: mvn test
#        -Dtest=!SignUpTest
